import { Hono } from "hono";
import nunjucks from "nunjucks";
import { serveStatic } from "@hono/node-server/serve-static";
nunjucks.configure({ autoescape: false });
const login_comp = `<login-></login->`;
const callback_comp = `<callback-></callback->`;
const callback = nunjucks.render("layout.html", { component: callback_comp });
let login = nunjucks.render("layout.html", { component: login_comp });
const app = new Hono();
app.use("*", serveStatic({ root: "./static" }));
console.log(login);
app.get("/login", (c) => c.html(login));
app.get("/callback", (c) => c.html(callback));
export default app;
